# Generated by Django 4.2.5 on 2023-10-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppNotas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotasGuardadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Categoria",
            new_name="EliminarNota",
        ),
        migrations.RenameModel(
            old_name="Usuario",
            new_name="CrearNota",
        ),
        migrations.DeleteModel(
            name="Nota",
        ),
        migrations.AddField(
            model_name="notasguardadas",
            name="creador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppNotas.crearnota"
            ),
        ),
    ]
