# Generated by Django 4.2.5 on 2023-10-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppNotas", "0003_crearnota_camada"),
    ]

    operations = [
        migrations.AddField(
            model_name="crearnota",
            name="curso",
            field=models.CharField(default="", max_length=40),
        ),
    ]
