# Generated by Django 4.2.5 on 2023-10-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppNotas", "0004_crearnota_curso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crearnota",
            name="camada",
        ),
        migrations.RemoveField(
            model_name="crearnota",
            name="curso",
        ),
    ]
