# Generated by Django 4.2.5 on 2023-10-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppNotas", "0005_remove_crearnota_camada_remove_crearnota_curso"),
    ]

    operations = [
        migrations.CreateModel(
            name="EliminarNotaForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(default="Sin título", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="crearnota",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="crearnota",
            name="email",
        ),
        migrations.RemoveField(
            model_name="crearnota",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="eliminarnota",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="eliminarnota",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="notasguardadas",
            name="contenido",
        ),
        migrations.RemoveField(
            model_name="notasguardadas",
            name="creador",
        ),
        migrations.RemoveField(
            model_name="notasguardadas",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="notasguardadas",
            name="fecha_creacion",
        ),
        migrations.AddField(
            model_name="crearnota",
            name="titulo",
            field=models.CharField(default="Sin título", max_length=100),
        ),
        migrations.AddField(
            model_name="eliminarnota",
            name="titulo",
            field=models.CharField(default="Sin título", max_length=100),
        ),
        migrations.AlterField(
            model_name="notasguardadas",
            name="titulo",
            field=models.CharField(default="Sin título", max_length=100),
        ),
    ]
